<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invalid username or password__9lsa</name>
   <tag></tag>
   <elementGuidId>e8441842-2b28-4dcf-bf90-f61a980412ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._9lsa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_3_jq']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c25b56a8-c51d-4588-8db6-abfe809a6f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9lsa</value>
      <webElementGuid>dfd873cb-7fcc-4822-9e31-76762db1cee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_3_jq&quot;)/a[1]/div[@class=&quot;_9lsa&quot;]</value>
      <webElementGuid>a35a5af9-8441-4b27-87ad-4772717c1586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_3_jq']/a/div</value>
      <webElementGuid>1ce621e9-d8c1-454b-8e02-c842c92cc117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid username or password'])[1]/following::div[7]</value>
      <webElementGuid>7ab2b689-7c80-4f92-9952-e16b9787b73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wrong credentials'])[1]/following::div[8]</value>
      <webElementGuid>02942539-4420-41be-af6c-018e9ebd9476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[2]</value>
      <webElementGuid>d4e84b14-741a-4778-ab3b-78c1e5e49c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/preceding::div[3]</value>
      <webElementGuid>3dfa2f37-959a-473c-91e3-28ea87616bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>7e77eb06-5737-4067-82ec-50cc2072cde9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
