<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Facebook helps you connect and share wi_41e91d</name>
   <tag></tag>
   <elementGuidId>b0fcc559-2eb0-4493-a084-6e56b79ed944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fb_logo._8ilh.img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad86eb84-7f71-433c-b038-ef21b57b43b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fb_logo _8ilh img</value>
      <webElementGuid>53b3f484-419f-44db-9124-e9b7ab3b9a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.xx.fbcdn.net/rsrc.php/y8/r/dF5SId3UHWd.svg</value>
      <webElementGuid>74679626-62f9-42e8-a139-f847c8cd4c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>84a9e000-6e1e-4fd4-89cd-1eb3ccec8863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;_8esj _95k9 _8esf _8opv _8f3m _8ilg _8icx _8op_ _95ka&quot;]/div[@class=&quot;_8esk&quot;]/div[@class=&quot;_8esl&quot;]/div[@class=&quot;_8ice&quot;]/img[@class=&quot;fb_logo _8ilh img&quot;]</value>
      <webElementGuid>c0f2d952-7faa-4390-8a18-e9bfb52cdab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/img</value>
      <webElementGuid>84f6cc11-2c9e-4bb6-878c-32018324e59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Facebook']</value>
      <webElementGuid>96b453ad-9682-445c-ac44-728adad93dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0e956803-4e31-4a81-bf66-ab70b47b7ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.xx.fbcdn.net/rsrc.php/y8/r/dF5SId3UHWd.svg' and @alt = 'Facebook']</value>
      <webElementGuid>a72f7547-cc6a-4095-9dbd-8d9d3e3ba453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
